version: '2'
services:
  zookeeper:
    image: wurstmeister/zookeeper:3.4.6
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka:0.10.2.1
    links:
     - zookeeper
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "simpletopic:5:1"
 
  # Our Redis service:
  redis:  
    image: redis
    volumes:
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    ports:
      - "6379"

  eureka:
    build: microservicepoc-eureka-server
    ports:
    - "8761:8761"
  fms:
    build: microservicepoc-fms
    ports:
    - "8081:8081"    
    links:
    - eureka
  assetcatalog:
    build: microservicepoc-assetcatalog
    ports:
    - "8072:8072"    
    links:
    - eureka