version: '2'
services:
  zookeeper:
    image: wurstmeister/zookeeper:3.4.6
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka:0.10.2.1
    links:
     - zookeeper
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "simpletopic:5:1"
 
  # Our Redis service:
  redis:
    image: redis
    ports:
      # We'll bind our host's port 6379 to redis's port 6379, so we can use
      # Redis Desktop Manager (or other tools) with it:
      - 6379:6379
    volumes:
      # We'll mount the 'redis-data' volume into the location redis stores it's data:
      - redis-data:/var/lib/redis
    command: redis-server --appendonly yes

  eureka:
    build: microservicepoc-eureka-server
    ports:
    - "8761:8761"
  fms:
    build: microservicepoc-fms
    ports:
    - "8081:8081"    
    links:
    - eureka
  assetcatalog:
    build: microservicepoc-assetcatalog
    ports:
    - "8072:8072"    
    links:
    - eureka